services:
  webfloodit:
    environment:
      TZ: PST8PDT
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Containerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
