version: "3.8"
services:
  webfloodit:
    # image: klmcwhirter/webfloodit:latest
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
